config/routes.rb
CnpWeb::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'users/registrations', :sessions => 'users/sessions'}

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  devise_for :student, :controllers => {:registrations => 'student/registrations', :sessions => 'student/sessions'}

  devise_scope :student do
    get 'student/sign_out', to: 'student/sessions#destroy', as: :destroy_student_session , via:Devise.mappings[:student].sign_out_via
  end

  authenticated :student do
    root :to => 'students#index'
    match '/resume', :to => 'resume#index', via: [:get, :post]
    match '/resume/upload', to: 'resume#upload_file', via: [:get, :post]
    match 'companies/profile', to: 'companies#profile', via: [:get ,:post]
  end

  devise_for :admin, :controllers => {:registrations => 'admin/registrations', :sessions => 'admin/sessions'}

  devise_scope :admin do
    get 'admin/sign_out', to: 'admin/sessions#destroy', as: :destroy_admin_session , via:Devise.mappings[:admin].sign_out_via
  end

  authenticated :admin do
    root :to => 'admin#index'
    match '/resume', :to => 'resume#index', via: [:get, :post]
    match '/resume/upload', to: 'resume#upload_file', via: [:get, :post]
    match '/admin/company', to: 'admin#company', via: [:get, :post]
    match '/admin/mail', to: 'admin#mail', via: [:get, :post]
    match '/admin/student', to: 'admin#student', via: [:get, :post]
    match '/admin/reports', to: 'admin#reports', via: [:get, :post]
  end

  match '/forums', to: 'forum#index', via: [:get]

  match '/my_profile', to: 'profile#my_profile', via: [:get, :post]

  match 'messages', to: 'profile#messages'

  match 'companies', to: 'companies#index', via: [:get, :post]
  resources :home, :companies, :resume

  resources :forum do
    resources :comments
  end

  root :to => 'home#index'
  

end

app/models/admin.rb
class Admin < User
  # attr_accessible :title, :body

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |student|
        csv << student.attributes.values_at(*column_names)
      end
    end
  end

  def self.upload_file(file_name, year_id)

  end
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :name
  has_many :stud_degree_infos, :foreign_key => :branch_id, dependent: :delete_all

  validates_uniqueness_of :name
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  validates_uniqueness_of :name

  has_many :users, :foreign_key => :category_id
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :forum
  attr_accessible :body, :commenter, :email

  validates :email, presence: true, length: {minimum: 8}
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :category, :job_type_id, :location, :name, :profile, :requirement, :arrival_date

  has_many :stud_comp_regs, foreign_key: :company_id, :dependent => :destroy
  has_many :students, through: :stud_comp_regs

  belongs_to :job_type
  validates_uniqueness_of :name, :scope => :job_type_id

  def self.search(name, job_type)
    if name
      find(:all, :conditions => ['name LIKE ? AND job_type_id = ?', "#{name}%", "#{job_type}"])
    else
      find(:all, :conditions => ['job_type_id = ?', "#{job_type}"])
    end
  end

end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
  attr_accessible :college_email, :personal_email, :phone_number1, :phone_number2, :user_id

  belongs_to :user

  validates_uniqueness_of :user_id
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  # attr_accessible :title, :body

  def self.save(file_name)
   # name = upload['datafile'].original_filename
    directory = "lib/resumes"
    #create file path

    path = File.join(directory, file_name)

    #write the file
    File.open(path, "wb") {
      |f| f.write(file_name)
    }
  end
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  attr_accessible :duration, :name

  has_many :stud_degree_info, :foreign_key => :degree_id, :dependent => :delete_all
  validates_uniqueness_of :name
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :content, :title

  has_many :comments
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  attr_accessible :name

  validates_uniqueness_of :name

  has_many :companies, foreign_key: :job_type_id
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :name, :student_id, :updated_at

  belongs_to :student

  validates_uniqueness_of :student_id, :scope => :name

  def self.upload(student_id, file_name)
    puts "Directory number: \n\n #{directory = "lib/resumes/#{student_id}"} \n\n"
    path = File.join(directory, file_name)
    #write the file
    File.open(path, "wb") {|file| file.write(file_name)}

    puts "file name : ------------ #{file_name} \n\n"

    saved = Resume.create(name: file_name, student_id: student_id).save
    unless saved
      cur_resume = Resume.where("name LIKE '#{file_name}%' and student_id = #{student_id}")[0]
      #Resume.update(cur_resume.id, updated_id: Time.now)
      cur_resume.updated_at = Time.now
      cur_resume.save
    end

  end

  def self.search(student_id, name)
    if name
      find(:all, :conditions => ['name LIKE ? AND student_id = ?', "%#{name}%", "#{student_id}"])
    else
      find(:all, :conditions => ['student_id = ?', "#{student_id}"])
    end
  end

end

app/models/stud_comp_reg.rb
class StudCompReg < ActiveRecord::Base
  attr_accessible :company_id, :placed, :selected, :shortlisted, :student_id, :resume_id

  belongs_to :student, :class_name => 'Student'
  belongs_to :company, :class_name => 'Company'

  validates_uniqueness_of :student_id, scope: :company_id

  def self.create_registration(student_id, company_id, resume_id)
    StudCompReg.create(student_id: student_id, company_id: company_id, resume_id: resume_id)
  end
end

app/models/student.rb
class Student < User
  # attr_accessible :title, :body
  has_many :stud_comp_regs, foreign_key: :student_id, :dependent => :destroy
  has_many :companies, through: :stud_comp_regs
  has_many :resumes, foreign_key: :student_id, :dependent => :destroy
  has_one :stud_degree_info, :foreign_key => :student_id, :dependent => :destroy
  belongs_to :year_of_graduation

  after_create :create_details

  def create_details
    ContactInfo.create(user_id: self.id)
    StudDegreeInfo.create(student_id: self.id)
    %x(mkdir lib/resumes/"#{self.id}")
  end

  def self.search(name)
    if name.nil? == false and name.empty? == false
      find(:all, :conditions => ['first_name LIKE ?', "%#{name}%"])
    else
      find(:all)
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |student|
        csv << student.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :contact_info, :foreign_key => :user_id, :dependent => :delete
  belongs_to :category
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :type, :first_name, :middle_name, :last_name,
                  :dob, :gender, :hostel_name, :hostel_address, :city, :state, :perm_citz_of_india, :category_id, :year_of_graduation_id
  # attr_accessible :title, :body
  before_create :check_name
  after_create :create_contact_info

  def check_name
    if self.first_name.nil?
      if self.kind_of? Student
        self.first_name = "User"
      else
        self.first_name = "Admin"
      end
    end
  end

  def create_contact_info
    ContactInfo.create(user_id: self.id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/company.html.erb
<% if flash[:message] %>
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= flash[:message] %>
</div>
<% end %>

<% if flash[:application_error] %>
<div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= flash[:application_error] %>
</div>
<% end %>

<div style="margin-left: 0%">
<%= form_tag  :url=> {:action => :company}, :method => 'get' do %>

  <!-- text_field_tag :search1, params[:search1], :placeholder => "Enter points to transfer: " -->

  <table class="table table-striped" style="width: 100%">
    <thead>
    <tr>
      <th>Company Name</th>
      <th>Job Type</th>
      <th>Branch</th>
    </tr>
    </thead>

    <tbody>
        <tr>
          <td>
            <%= select_tag 'company_name', options_for_select(@applied_companies, @c_name),include_blank: :true %>
          </td>

          <td>
            <%= select_tag 'job_type_name', options_for_select(@job_type, @j_name) %>
          </td>

          <td>
            <%= select_tag 'branch_name', options_for_select(@branch_name, @b_name), :include_blank => true%>
          </td>

        </tr>

    </tbody>
  </table>

  <!--= text_field_tag :sql_query, params[:sql_query], :placeholder => "Search Companies" -->

  <button style="margin-left: 1%;" class="btn" value="filter" name="filter" type="submit">Filter</button>

      <p/>
      <br/>
      <div style="font-family: Georgia; font-size: 20px">Application Status</div>
      <table class="table table-striped" style="width: 100%">
        <thead>
        <tr>
          <th>Select </th>
          <th>Company Name</th>
          <th>Enrolment Number</th>
          <th>Student Name</th>
          <th>Branch</th>
          <th>Shortlisted</th>
          <th>Selected</th>
        </tr>
        </thead>

        <tbody>
        <% @applications.each do |app| %>
            <tr>
              <td>
                <%= check_box_tag "application_ids[]", app.id %>
              </td>

              <td>
               <%= Company.find(app.company_id).name %>
              </td>
              <td>
                <% @st = Student.find(app.student_id)  %>
                <%= @st.stud_degree_info.enrolment_number %>
              </td>

              <td><%= "#{@st.first_name} #{@st.last_name}" %></td>

              <% @branch_id = @st.stud_degree_info.branch_id %>
              <td>
                <% unless @branch_id.nil? %>
                    <%= Branch.find(@branch_id).name %>
                <% end %>
              </td>

              <td>
                <% if app.shortlisted.nil? %>
                    <%= select_tag 'shortlist[]', options_for_select([["YES", "true,#{app.id}"], ["NO", "false,#{app.id}"]]), :include_blank => true %>
                <% else %>
                    <% if app.shortlisted == true %>
                        <%= select_tag 'shortlist', options_for_select([["YES"], ["NO"]]), :disabled => true %>
                    <% else %>
                        <%= select_tag 'shortlist', options_for_select([["NO"]]), :disabled => true %>
                    <% end %>
                <% end %>
              </td>

              <td>
                <% if app.selected.nil? %>
                    <%= select_tag 'select[]', options_for_select([["YES", "true,#{app.id}"], ["NO", "false,#{app.id}"]]), :include_blank => true %>
                <% else %>
                    <% if app.selected == true %>
                        <%= select_tag 'select[]', options_for_select([["YES"], ["NO"]]), :disabled => true %>
                    <% else %>
                        <%= select_tag 'select[]', options_for_select([["NO"]]), :disabled => true %>
                    <% end %>
                <% end %>
              </td>

              <br/>
            </tr>
        <% end %>
        </tbody>
      </table>

      <div><button style="margin-left: 0%;" class="btn" value="save_detail" name="save_detail" type="submit">Save Details</button>
      </div>

      <br/>
      <%= text_field_tag :archive_name, params[:archive_name], :placeholder => "Archive name .. " %>
      <br/>
      <%= submit_tag 'Download' %>
<% end %>
</div>

app/views/admin/index.html.erb
Welcome!

app/views/admin/mail.html.erb
<form accept-charset="UTF-8" class="form" method="post" style="margin-left: 2%">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

  <div class="control-group">
    <div class="controls">
      <input type="search" name="student_name" placeholder="Search for a student: " value="<%= @s_name %>">
    </div>
    <button  type="submit" class="btn btn-default" name="search_student">Search</button>
  </div>

  <table class="table table-bordered" style="width: 100%">
    <thead>
    <tr>
      <th>#</th>
      <th>Student Name</th>
      <th>Enrolment Number</th>
      <th>Branch</th>
      <th>Degree</th>
      <th>Year of Graduation</th>
    </tr>
    </thead>

    <tbody>
    <% @students.each_with_index do |student, index| %>
        <tr>

          <td>
            <%= check_box_tag "student_ids[]", student.id %>
          </td>

          <td>
            <%= "#{student.first_name} #{student.last_name}" %>
          </td>

          <td>
            <%= student.stud_degree_info.enrolment_number %>
          </td>

          <% @branch_id = student.stud_degree_info.branch_id %>
          <td>
            <% unless @branch_id.nil? %>
                <%= Branch.find(@branch_id).name %>
            <% end %>
          </td>

          <% @degree_id = student.stud_degree_info.degree_id %>
          <td>
            <% unless @degree_id.nil? %>
                <%= Degree.find(@degree_id).name %>
            <% end %>
          </td>

          <td>
            <%= student.stud_degree_info.year_of_grad %>
          </td>
          <br/>
        </tr>
    <% end %>
    </tbody>
  </table>


  <div class="control-group">
    <div class="controls">
      <textarea name="message" placeholder="Please enter your message here .. " value=""></textarea>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <button  type="submit" class="btn btn-small" name="send_mail">Send Mail ..</button>
    </div>
  </div>


</form>

<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @students %>
  </div>
  <%= will_paginate @students, :container => false %>
</div>

app/views/admin/reports.html.erb
<% if flash[:upload_error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:upload_error] %>
    </div>
<% end %>

<div style="margin-left: 1%">
  <%= form_tag  :url=> {:action => :reports}, :method => 'get' do %>

      <!-- text_field_tag :search1, params[:search1], :placeholder => "Enter points to transfer: " -->

      <table class="table" style="width: auto;">
        <thead>
        <tr>
          <th>Company Name</th>
          <!-- <th>Branch</th> -->
        </tr>
        </thead>

        <tbody>
        <tr>
            <!-- select_tag 'job_type_name', options_for_select(@job_type, @j_name), :include_blank => true -->

          <td>
            <%= select_tag 'company_name', options_for_select(@companies, @comp_name), :include_blank => false %>
          </td>

         <!-- <td>
            <= select_tag 'branch_name', options_for_select(@branch_name, @b_name), :include_blank => true %>
          </td>
          -->
        <td>

          <button class="btn" type="submit" name="company_submit" value="" formaction="<%= admin_reports_path(format: 'csv') %>" >Download CSV</button>

        </td>
        </tr>

        </tbody>
      </table>

      <br/>


      <table class="table" style="width: auto;">
        <thead>
        <tr>
          <th>Year of Graduation</th>
          <!-- <th>Branch</th> -->
        </tr>
        </thead>

        <tbody>
        <tr>
          <!-- select_tag 'job_type_name', options_for_select(@job_type, @j_name), :include_blank => true -->

          <td>
            <%= select_tag 'year_number', options_for_select(@year_of_grads, @year_grad_number), :include_blank => false %>
          </td>

          <!-- <td>
             <= select_tag 'branch_name', options_for_select(@branch_name, @b_name), :include_blank => true %>
           </td>
           -->
          <td>
            <button class="btn" type="submit" name="year_submit" formaction="<%= admin_reports_path(format: 'csv') %>" value="" >Download</button>
          </td>

        </tr>

        <tr>
          <td>
            <input type="file" id="upload_datafile" name="upload[datafile]" > <br/>
            <br/>
            <button class="btn" name="upload_data" type="submit">Upload CSV</button>
          </td>
        </tr>

        </tbody>
      </table>

      <!-- link_to "CSV", admin_reports_path(format: "csv") -->

        <!-- link_to "Excel", admin_reports_path(format: "xls") -->

      <!--= text_field_tag :sql_query, params[:sql_query], :placeholder => "Search Companies" -->

  <% end %>
 </div>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CnpWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<script type="text/javascript">
    WebFontConfig = {
        google: { families: [ 'Allura::latin', 'Gilda Display', 'Gabriela', 'Esteban', 'Droid Serif','Fanwood Text' ] }
    };
    (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
    })(); </script>

<div class="navbar">
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <!-- <a class="brand" href="#">Title</a> -->

      <ul class="nav">

        <li><a href="/">Home</a></li>
        <li class="divider-vertical"></li>
        <li><a href=<%= forums_path %>>Forums</a></li>
        <li class="divider-vertical"></li>
        <li><a href=<%= admin_company_path %>>Company</a></li>
        <li class="divider-vertical"></li>
        <!--<li><a href=<= admin_student_path %>>Student</a></li>
        <li class="divider-vertical"></li>
        -->
        <li><a href=<%= admin_mail_path %>>Mail</a></li>
        <li class="divider-vertical"></li>
        <li><a href=<%= admin_reports_path %>>Report</a></li>
        <li class="divider-vertical"></li>
      </ul>

      <ul class="nav pull-right">
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_admin.first_name %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
          <li><a href="<%= destroy_admin_session_path %>">Sign Out</a></li>
          </ul>

        </li>

      </ul>
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CnpWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<script type="text/javascript">
    WebFontConfig = {
        google: { families: [ 'Allura::latin', 'Gilda Display', 'Gabriela', 'Esteban', 'Droid Serif','Fanwood Text' ] }
    };
    (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
    })(); </script>

<% if user_signed_in? %>
 Signed in as <%= current_user.email %>
<% end %>
<div class="navbar">
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <!-- <a class="brand" href="#">Title</a> -->

      <ul class="nav">

        <li><a href="/">Home</a></li>
        <li class="divider-vertical"></li>
        <li><a href=<%= forums_path %>>Forums</a></li>
        <li class="divider-vertical"></li>
      </ul>
      <ul class="nav pull-right">
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
             User
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% unless user_signed_in? %>
                <li><a href="<%= new_user_session_path %>"> Sign In</a> </li>
                <li><a href="<%= new_user_registration_path %>"> Sign Up</a> </li>
          <% else %>
                <li><a href="<%= my_profile_path %>">My Profile</a></li>
                <li><a href="<%= destroy_user_session_path %>">Sign Out</a></li>
            <% end %>
          </ul>

        </li>

        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            Admin
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% unless user_signed_in? %>
                <li><a href="<%= new_admin_session_path %>"> Sign In</a> </li>
            <% else %>
                <li><a href="<%= my_profile_path %>">My Profile</a></li>
                <li><a href="<%= destroy_admin_session_path %>">Sign Out</a></li>
            <% end %>
          </ul>

        </li>
      </ul>
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/student_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CnpWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<script type="text/javascript">
    WebFontConfig = {
        google: { families: [ 'Allura::latin', 'Gilda Display', 'Gabriela', 'Esteban', 'Droid Serif','Fanwood Text' ] }
    };
    (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
    })(); </script>

<div class="navbar">
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <!-- <a class="brand" href="#">Title</a> -->

      <ul class="nav">

        <li><a href="/">Home</a></li>
        <li class="divider-vertical"></li>
        <li><a href=<%= forums_path %>>Forums</a></li>
        <li class="divider-vertical"></li>
        <li><a href=<%= companies_path %>>Companies</a></li>
        <li class="divider-vertical"></li>
        <li><a href=<%= resume_path %>>Resume</a></li>
        <li class="divider-vertical"></li>
      </ul>
      <ul class="nav pull-right">
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown">
            <% if student_signed_in? %>
                <%= current_student.first_name %>
            <% elsif admin_signed_in? %>
                <%= current_admin.first_name %>
            <% end %>
            <b class="caret"></b>
          </a>

          <ul class="dropdown-menu">
            <li><a href="<%= my_profile_path %>">My Profile</a></li>
            <li><a href="<%= edit_student_registration_path %>">Change Password</a></li>
            <li><a href="<%= destroy_student_session_path %>">Sign Out</a></li>
          </ul>

        </li>
      </ul>
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/user_layout.html.erb
<% render 'application' %>