config/routes.rb
CnpWeb::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'users/registrations', :sessions => 'users/sessions'}

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  devise_for :student, :controllers => {:registrations => 'student/registrations', :sessions => 'student/sessions'}

  devise_scope :student do
    get 'student/sign_out', to: 'student/sessions#destroy', as: :destroy_student_session , via:Devise.mappings[:student].sign_out_via
  end

  authenticated :student do
    root :to => 'students#index'
    match '/resume', :to => 'resume#index', via: [:get, :post]
    match '/resume/upload', to: 'resume#upload_file', via: [:get, :post]
    match 'companies/profile', to: 'companies#profile', via: [:get ,:post]
  end

  devise_for :admin, :controllers => {:registrations => 'admin/registrations', :sessions => 'admin/sessions'}

  devise_scope :admin do
    get 'admin/sign_out', to: 'admin/sessions#destroy', as: :destroy_admin_session , via:Devise.mappings[:admin].sign_out_via
  end

  authenticated :admin do
    root :to => 'admin#index'
    match '/resume', :to => 'resume#index', via: [:get, :post]
    match '/resume/upload', to: 'resume#upload_file', via: [:get, :post]
    match '/admin/company', to: 'admin#company', via: [:get, :post]
    match '/admin/mail', to: 'admin#mail', via: [:get, :post]
    match '/admin/student', to: 'admin#student', via: [:get, :post]
    match '/admin/reports', to: 'admin#reports', via: [:get, :post]
  end

  match '/forums', to: 'forum#index', via: [:get]

  match '/my_profile', to: 'profile#my_profile', via: [:get, :post]

  match 'messages', to: 'profile#messages'

  match 'companies', to: 'companies#index', via: [:get, :post]
  resources :home, :companies, :resume

  resources :forum do
    resources :comments
  end

  root :to => 'home#index'
  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :content, :title

  has_many :comments
end

app/controllers/forum_controller.rb
require 'will_paginate/array'

class ForumController < ApplicationController
  before_filter :admin_privilege, :only => [:new, :create]
  layout :check_user

  private
  def check_user
    if student_signed_in?
      'student_layout'
    else
      'admin_layout'
    end
  end

  public
  def new
    forum = Forum.new
  end

  def create
    forum = Forum.new(params[:forum])

    respond_to do |format|
      format.html {render}
      format.json {render :json}
    end
  end

  def edit
    @forum = Forum.find(params[:id])
  end

  def index
    @forums = Forum.all
    @forums = @forums.paginate(page: params[:page], per_page: 5 )
    respond_to do |format|
      format.html {render }
      format.json {render :json}
    end
  end

  def show
    @forum = Forum.find(params[:id])
    @comments = @forum.comments

    respond_to do |format|
      format.html {render}
      format.json {render :json}
    end

  end
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/views/forum/index.html.erb
<br/>
<div class="" style="margin-left: 100px; margin-right: 100px; background-color: transparent; height: 400px; border-color: transparent">
  <div  style="font-family: Georgia; text-align: center; font-size: 60px; color: lightslategray"> Forums </div>

  <div class="row" style="padding-top: 5%; margin-left: 5%; margin-right: 5%">
    <ul>
      <div class="accordion" style="font-size: 20px; color: #000000">

        <% @forums.each do |forum| %>
            <li> <p><a href="<%= forum_path(forum) %>" style="font-family: 'Gabriela'; font-size: 20px; background-color: transparent;
                    color: blue ;margin-top: 10% ; color: #000000"> <%= forum.title %></a> </p> </li>
            <br/>
        <% end %>

        <!-- if @forums.empty? -->
        <!-- end -->

      </div>

    </ul>
  </div>

  <div class="apple_pagination" style="padding-bottom: 8%  ; width: 30%; background-color: transparent; border-color: transparent;
          text-align: center; margin-left: 34%; color: #2d6987">
    <div class="page_info" style="font-family: Consolas; color: #000000">
      <%= page_entries_info @forums %>
    </div>
    <%= will_paginate @forums, :container => false %>
  </div>

</div>

app/views/forum/show.html.erb
<div class="forum_class" style="margin-top: -30px">


  <ul class="pager" style="padding-left: 20px; padding-right: 20px">
    <% if @forum.id.to_i == Forum.all.first.id %>
        <li class="previous disabled">
          <a href="#" disabled style="background-color: transparent; border-color: transparent; padding-top: 5px">&larr; Previous</a>
    <% else %>
        <li class="previous">
          <a href="<%= forum_path(@forum.id.to_i - 1) %>" style="background-color: transparent; color: #006688 ; ;border-color: transparent; padding-top: 5px">&larr; Previous</a>
    <% end %>
    </li>

    <% if Forum.all.last.id == @forum.id.to_i %>
        <li class="next disabled">
          <a href="#" disabled style="background-color: transparent; border-color: transparent; padding-top: 5px">Next &rarr;</a>
    <% else %>
        <li class="next">
          <a href="<%= forum_path(Forum.find(@forum.id.to_i + 1))%>" style="background-color: transparent; color: #006688; border-color: transparent; padding-top: 5px">Next &rarr;</a>
    <% end %>
    </li>
  </ul>

  <div class="accordion" style="text-align: center ;color: #2d6987; font-size: 40px; margin-top: -20px  ;font-family: 'Consolas'; text-decoration: underline">  <%= @forum.title %>    </div>
  <div class="accordion" style="padding-left: 40px; padding-right: 40px; padding-top: 20px; font-family: 'lucida console'; font-size: 15px ;text-wrap: normal"> <%= @forum.content %>  </div>

</div>

<div style="margin-bottom: 30%; margin-left: auto; margin-right: auto; width: 76%">
  <form id="new_comment" style="background-color: transparent; border-color: transparent" class="well span8" method="post" action="/forum/<%= @forum.id.to_i %>/comments" accept-charset="UTF-8">

    <div class="row" style="margin-left: auto; margin-right: auto;">
      <h2 style="color: darkslategrey; font-family: Consolas; font-size: 16px">Add a comment
        <% unless user_signed_in? %>
            <!--    (please login or the fill in the form below to post a comment) -->
        <% end %>
        :
      </h2>

      <hr style="width: 61% ; margin-top: auto; background-color: #000000; border-color: darkslategrey"/>

      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

      <div class="span3" style="margin-left: auto">
        <p><textarea name="comment[body]" id="comment_body" class="input-xlarge span5" rows="10" style="margin-top: 5% ;height: 100px" placeholder="Enter your comment here..."></textarea>
        </p>

        <br/>

        <p><div style = "margin-right: -50%; color: darkslategrey; text-decoration: solid; font-family: 'Consolas' ;font-size: 16px;">
        <% unless user_signed_in? %>
            Fill in your details below or login <a href="<%= new_user_session_path %>" style="color: #002a80"> here. </a>
        <% end %>
      </div>
        </p>
        <input style="margin-top: 5%" id="comment_commenter" type="text" class="span5" placeholder="Your Full Name *" name="comment[commenter]" autofocus="true">


        <% unless user_signed_in? %>
            <input style="margin-top: 5%" id="comment_email" type="email" class="span5" placeholder="Your email *" name="comment[email]">
        <% else %>
            <input style="margin-top: 5%" id="comment_email" type="email" class="span5" placeholder="Your email *" name="comment[email]" value="<%= current_user.email %>">
        <% end %>

        <button name="commit" value="Send" type="submit" class="btn" style="margin-top: 5%;font-family: Consolas; color: darkslategrey; margin-left: 320px">Post</button>

      </div>
    </div>
  </form>
</div>

<div class="panel-group" id="accordion" style="padding-top: 6% ;padding-left: 20px; padding-right: 20px; width: 70%; margin-left: auto; margin-right: auto">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#view_comments" style="color: steelblue; font-size: 16px; font-family: Gabriel">
          View Comments
        </a>
      </h4>
    </div>

    <div id="collapseOne" class="panel-collapse collapse in" style="margin-top: 20px">    <!-- collapse in  -->
      <div class="panel-body">
        <ul>
          <% @forum.comments.each do |comment| %>

              <li>
                <div style="text-wrap: normal; font-size: 14px; font-family: Consolas"><strong> <%= comment.commenter %> </strong></div>
                <div style="text-wrap: normal; font-size: 14px; font-family: Consolas">  <%= comment.body %></div>
              </li>
              <br/>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

</div>

<!--<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">
  simple collapsible
</button>

<div id="demo" class="collapse in">...</div>
-->